version: "3"
services:
    elk_reverseproxy:
        image: nginx:1.14.1-alpine
        ports:
        - '5601:82'
        - '9200:84'
       
        depends_on:
        - kibana
        
        volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d/
        networks:
        - elknetwork
    elasticsearch:
        image: elasticsearch:7.7.0
        container_name: elasticsearch
        hostname: elasticsearch
        environment:
            - "discovery.type=single-node"
        #ports:
         # - 9200:9200
         #- 9300:9300
        volumes:
        - ./elasticsearch/elasticsearch.yml:/config/elasticsearch.yml 
        networks:
            - elknetwork
    kibana:
        image: kibana:7.7.0
        container_name: kibana
        hostname: kibana
       # ports:
       # - 5601:5601
        links:
            - elasticsearch:elasticsearch
        
        depends_on:
          - elasticsearch
        networks:
          - elknetwork
    logstash:
        image: logstash:7.7.0
        container_name: logstash
        hostname: logstash
        ports:
            - 9600:9600
            - 8089:8089
        volumes:
          - ./logstash:/usr/share/logstash/pipeline/
        links:
            - elasticsearch:elasticsearch
       
        networks:
          - elknetwork
networks:
    elknetwork:
        driver: bridge

